source 'https://rubygems.org'

gem 'sinatra', '~> 2.0'
gem 'jwt', '~> 2.1'
gem 'octokit', '~> 4.25'
gem 'dotenv'
gem 'thin'
gem 'puma'
gem 'reel'
gem 'http'
gem 'webrick'
gem 'sinatra-contrib'
gem 'faraday-retry'
